Rd 886 add wrappers workflows
cloudify-incubator/cloudify-utilities-plugin pull request #224
Opened 2021-01-03 09:05 UTC by AdarShaked

2021-01-03 11:26 UTC, AdarShaked commented on cloudify_rollback_workflow/workflows.py
> +    start(ctx, start_parms, run_by_dependency_order, type_names,
I don`t know if its good or not but as i think of it, if user wants to run restart with ignore failure he wants the stop will ignore_failure only.
i did what i think its the best but i can either:
 split it to` ignore_failure_start` and `ignore_failure_restart` parameters.
 or just pass `ignore_failure` to both start and stop.
 What is your opinion?

2021-01-04 10:23 UTC, EarthmanT requested changes

2021-01-04 10:23 UTC, EarthmanT commented on plugin.yaml
> +  wrap_start:
Change name to `alt_start` ... and all the others to `alt_...` What do you think?

2021-01-04 12:06 UTC, EarthmanT approved these changes

2021-01-10 11:29 UTC, merged